#!/bin/bash

ENTANDO_ENT_ACTIVE_NEW=$(
  if [ -n "$BASH_VERSION" ]; then
    if [ -f "${BASH_SOURCE[0]}.ln" ]; then
      SS="$(cat "${BASH_SOURCE[0]}.ln")"
    else
      SS="$(readlink --canonicalize --no-newline "${BASH_SOURCE[0]}")"
      [ -z "$SS" ] && SS="${BASH_SOURCE[0]}";
    fi
    cd "$( dirname "${SS}" )" >/dev/null 2>&1 && pwd
  elif [ -n "$ZSH_VERSION" ]; then
    dirname "$0:A"
  else
    echo "Unsupported shell, user either bash or zsh" 1>&2 && return 99
    echo ""
  fi
)

[ "$ENTANDO_ENT_ACTIVE_NEW" = "" ] && exit 99

(
 [[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] || 
 [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
    printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] || 
 [[ -n $BASH_VERSION ]] && (return 0 2>/dev/null)
) || {
  P="$0"
  [[ ! "$P" =~ / ]] && P="./$P"
  echo "You need to source-execute me (\"source $P\")" 1>&2
  exit
}

[ "$ENTANDO_ENT_ACTIVE" != "" ] && {
  [[ "$1" != "--quiet" && "$2" != "--quiet" ]] && echo "An instance at location \"$ENTANDO_ENT_ACTIVE\" is already active (force with --force)"
  if [[ "$1" = "--force" || "$2" = "--force" ]]; then
    [[ "$1" != "--quiet" && "$2" != "--quiet" ]] && echo "FORCING ACTIVATION AS REQUESTED"
    if [ "$ENTANDO_ENT_ACTIVE" != "" ] ; then
      . "$ENTANDO_ENT_ACTIVE/deactivate" -p --force
    else
      . "$ENTANDO_ENT_ACTIVE/deactivate" -p --force > /dev/null 2>&1
    fi
  else
    [[ "$1" != "--quiet" && "$2" != "--quiet" ]] && echo "Quitting"
    return 91
  fi
}

ENTANDO_ENT_ACTIVE="$ENTANDO_ENT_ACTIVE_NEW"
export ENTANDO_ENT_ACTIVE
PATH="$ENTANDO_ENT_ACTIVE/bin:$PATH"
export PATH
unset ENTANDO_ENT_ACTIVE_NEW

[[ "$1" != "--quiet" && "$2" != "--quiet" ]] && echo "Version \"$ENTANDO_ENT_ACTIVE\" activated"
