#!/bin/bash

if [ -n "$BASH_VERSION" ]; then
  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
elif [ -n "$ZSH_VERSION" ]; then
  DIR="$(dirname "$0:A")"
else
  echo "Unsupported shell, user either bash or zsh" 1>&2 && return 99
fi

(
 [[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] || 
 [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
    printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] || 
 [[ -n $BASH_VERSION ]] && (return 0 2>/dev/null)
) && sourced=1 || sourced=0

if [[ "$sourced" == "0" ]]; then
  P="$0"
  [[ ! "$P" =~ / ]] && P="./$P"
  echo "You need to source-execute me (\"source $P\")" 1>&2
  exit
fi

[ "$ENTANDO_ENT_ACTIVE" != "" ] && echo "An instance at location \"$ENTANDO_ENT_ACTIVE\" is already active" && return 91

ENTANDO_ENT_ACTIVE="$DIR"
export ENTANDO_ENT_ACTIVE
PATH="$DIR/bin:$PATH"
export PATH
