#!/bin/bash

ENTANDO_ENT_ACTIVE_NEW=$(
  if [ -n "$BASH_VERSION" ]; then
    if [ -f "${BASH_SOURCE[0]}.ln" ]; then
      SS="$(cat "${BASH_SOURCE[0]}.ln")"
    fi
    [ -z "$SS" ] && SS="${BASH_SOURCE[0]}";
    cd "$( dirname "${SS}" )" >/dev/null 2>&1 && pwd
  elif [ -n "$ZSH_VERSION" ]; then
    dirname "$0:A"
  else
    echo "Unsupported shell, user either bash or zsh" 1>&2 && return 99
    echo ""
  fi
)

[ "$ENTANDO_ENT_ACTIVE_NEW" = "" ] && exit 99

# shellcheck disable=SC2154
(
 [[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] ||
 [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
    printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] ||
 [[ -n $BASH_VERSION ]] && (return 0 2>/dev/null)
) || {
  P="$0"
  [[ ! "$P" =~ / ]] && P="./$P"
  echo "You need to source-execute me (\"source $P\")" 1>&2
  exit
}

[ "$ENTANDO_ENT_ACTIVE" = "" ] && echo "No instance is currently active" && return 99
if [ "$ENTANDO_ENT_ACTIVE" != "$ENTANDO_ENT_ACTIVE_NEW" ]; then
  if [[ "$1" = "--force" || "$2" = "--force" ]]; then
    echo "Forcing deactivation of instance $ENTANDO_ENT_ACTIVE"
  else
    echo "This instance is not currently active (you may want to use --force)" && return 99
  fi
fi

PATH="${PATH//$ENTANDO_ENT_ACTIVE\/bin:/}"
unset ENTANDO_ENT_ACTIVE
[ "$1" != "-p" ] && unset ENTANDO_ENT_ACTIVE_NEW
