#!/bin/bash

[ -z "$ENTANDO_CLI_VERSION" ] && ENTANDO_CLI_VERSION="develop" && echo "Assuming ENTANDO_CLI_VERSION=\"$ENTANDO_CLI_VERSION\""
[ -z "$ENTANDO_NAMESPACE" ] && ENTANDO_NAMESPACE="entando" && echo "Assuming ENTANDO_NAMESPACE=\"$ENTANDO_NAMESPACE\""
[ -z "$ENTANDO_APPNAME" ] && ENTANDO_APPNAME="quickstart" && echo "Assuming ENTANDO_APPNAME=\"$ENTANDO_APPNAME\""
[ -z "$ENTANDO_WITH_VM" ] && ENTANDO_WITH_VM="true" && echo "Assuming ENTANDO_WITH_VM=\"$ENTANDO_WITH_VM\""
[ "$ENTANDO_RELEASE" == "" ] && ENTANDO_RELEASE="v6.2.0" && echo "Assuming ENTANDO_RELEASE=\"$ENTANDO_RELEASE\""

if [ "$ENTANDO_CLI_VERSION" = "develop" ] || [[ "$ENTANDO_CLI_VERSION" =~ ^exp-.+ ]]; then
  rm -rf "$HOME/.entando/ent/$ENTANDO_RELEASE/cli/$ENTANDO_CLI_VERSION/"
fi

curl -L "https://raw.githubusercontent.com/entando/entando-cli/$ENTANDO_CLI_VERSION/auto-install" \
  | ENTANDO_CLI_VERSION="$ENTANDO_CLI_VERSION" \
    ENTANDO_RELEASE="$ENTANDO_RELEASE" \
    bash

. ~/.entando/ent/"$ENTANDO_RELEASE"/cli/"$ENTANDO_CLI_VERSION"/deactivate --force > /dev/null
. ~/.entando/ent/"$ENTANDO_RELEASE"/cli/"$ENTANDO_CLI_VERSION"/activate

. ~/.entando/ent/"$ENTANDO_RELEASE"/cli/"$ENTANDO_CLI_VERSION"/s/sys-utils.sh

# shellcheck disable=SC2034
case "$OSTYPE" in
  linux*)
    DEV_TTY="/dev/tty"
    ;;
  darwin*)
    DEV_TTY="/dev/ttys000"
    ;;
  "cygwin" | "msys")
    DEV_TTY="/dev/tty"
    ;;
  win*)
    DEV_TTY="/dev/tty"
    ;;
  "freebsd" | "openbsd")
    DEV_TTY="/dev/tty"
    ;;
  *)
    DEV_TTY="/dev/tty"
    ;;
esac

(
  export ENTANDO_RELEASE
  export ENTANDO_VM_NAME
  export ENTANDO_VM_CPU
  export ENTANDO_VM_MEM
  export ENTANDO_VM_DISK
  export ENTANDO_OPT_YES_FOR_ALL=true

  if [ "$ENTANDO_WITH_VM" == "true" ] || [ "$ENTANDO_WITH_VM" == "multipass" ]; then
    ent-quickstart --with-vm --simple "$ENTANDO_NAMESPACE" "$ENTANDO_APPNAME"
  else
    ent-quickstart --simple "$ENTANDO_NAMESPACE" "$ENTANDO_APPNAME"
  fi
) < "$DEV_TTY"
