name: "Entando CI Docker images"

on:
  push:
    tags:
      - "v*"
    branches:
      - develop
      - release/*
      - ENG-*
      - ENGPM-*
      - IT-*

permissions: write-all

jobs:
  docker-buildx:
    name: Buildx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta-ent-cli-github
        id: meta-ent-cli-github
        uses: docker/metadata-action@v4
        with:
          # List of Docker Images to use as base name for tags
          images: |
            entando/ent-cli-github
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker meta-ent-cli-ocp
        id: meta-ent-cli-ocp
        uses: docker/metadata-action@v4
        with:
          # List of Docker Images to use as base name for tags
          images: |
            entando/ent-cli-ocp
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}
          password: ${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}

      - name: Build ent-cli-github
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta-ent-cli-github.outputs.tags }}
          build-args: |
            ENT_VERSION=${{ env.ENTANDO_RELEASE }}
            ENT_CLI_VERSION=${{ env.GITHUB_REF_NAME }}
          labels: ${{ steps.meta-ent-cli-github.outputs.labels }}
          platforms: linux/amd64

      - name: Build ent-cli-ocp
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta-ent-cli-ocp.outputs.tags }}
          build-args: |
            ENT_VERSION=${{ env.ENTANDO_RELEASE }}
            ENT_CLI_VERSION=${{ env.GITHUB_REF_NAME }}
          labels: ${{ steps.meta-ent-cli-ocp.outputs.labels }}
          platforms: linux/amd64
